# Generated by Django 5.1.3 on 2024-11-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('portfolio_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_ticker', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('current_price', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('house', models.CharField(max_length=50)),
                ('points_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('price_history_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItems',
            fields=[
                ('portfolio_item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolios')),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('timestamp', models.DateTimeField()),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stocks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='portfolios',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('earning_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
