# Generated by Django 5.1.3 on 2024-11-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_points_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='portfolioitems',
            old_name='portfolio_id',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='user_id',
            new_name='user',
        ),
    ]
